GET http://localhost:8080/api/users/100000

> {%
     client.test("Status shuld be 404", function (){
         client.assert(response.status === 404)
     });
%}

###
GET http://localhost:8080/api/users/1234

> {%
     client.test("Status shuld be 200", function (){
         client.assert(response.status === 200);

         client.assert(response.body.id === '1234');
         client.assert(response.body.name === 'taeil');
         client.assert(response.body.age === 29);
     });
%}
