version: '3'
services:
  mysql:
    image: mysql:8.0.31
    container_name: capo-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: r2dbc_practice

